// lib/cli/schema-doc.js — JSON Schema → Markdown generator (ADR-0015)
//
// usage:
//   vcm schema doc skill                              → stdout
//   vcm schema doc state --output docs/STATE-SCHEMA.md
//   vcm schema doc <path-in-repo>/<schema>.json       → stdout
//
// Implementation: pure stdlib walk of the JSON schema, emitting a
// table-style markdown. No third-party deps. ~80 LOC.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const VCM_ROOT = resolve(HERE, '..', '..');

const SCHEMA_ALIASES = {
  skill: 'lib/schemas/skill.schema.json',
  state: 'lib/schemas/state.schema.json',
};

/**
 * Resolve a user-facing key (e.g. "skill") or a path to a JSON Schema
 * file inside the vcm repo. Returns absolute path; throws on miss.
 */
function resolveSchemaPath(spec) {
  if (!spec) throw new Error('spec required (e.g. "skill" or "lib/schemas/foo.json")');
  if (SCHEMA_ALIASES[spec]) return resolve(VCM_ROOT, SCHEMA_ALIASES[spec]);
  // Try as relative path from cwd, then from repo root.
  try {
    return resolve(process.cwd(), spec);
  } catch (_) {}
  return resolve(VCM_ROOT, spec);
}

/**
 * Render JSON schema → Markdown. Returns a string.
 */
export function renderSchema(schema, title = 'Schema') {
  const lines = [];
  const id = (schema['$id'] || '').split('/').pop() || '';
  lines.push(`# ${title}`);
  lines.push('');
  if (schema.description) lines.push(`> ${schema.description}`);
  lines.push('');
  lines.push(`_Source: \`${id || '(no $id)'}\` · generated by \`vcm schema doc\`_`);
  lines.push('');

  // Required fields
  const required = schema.required || [];
  if (schema.properties) {
    const reqProps = Object.entries(schema.properties)
      .filter(([k]) => required.includes(k));
    if (reqProps.length) {
      lines.push('## Required fields');
      lines.push('');
      for (const [name, sub] of reqProps) {
        lines.push(renderField(name, sub));
      }
      lines.push('');
    }

    const optProps = Object.entries(schema.properties)
      .filter(([k]) => !required.includes(k));
    if (optProps.length) {
      lines.push('## Optional fields');
      lines.push('');
      for (const [name, sub] of optProps) {
        lines.push(renderField(name, sub));
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

function renderField(name, sub) {
  const out = [];
  out.push(`### \`${name}\``);
  out.push('');
  const typeStr = sub.type ? `\`${sub.type}\`` : '(no type)';
  out.push(`- type: ${typeStr}`);
  if (sub.description) out.push(`- ${sub.description}`);
  if (sub.enum) out.push(`- enum: ${JSON.stringify(sub.enum)}`);
  if ('default' in sub) out.push(`- default: \`${JSON.stringify(sub.default)}\``);
  if (sub.minimum !== undefined) out.push(`- minimum: \`${sub.minimum}\``);
  if (sub.maximum !== undefined) out.push(`- maximum: \`${sub.maximum}\``);
  if (sub.minLength !== undefined) out.push(`- minLength: \`${sub.minLength}\``);
  if (sub.maxLength !== undefined) out.push(`- maxLength: \`${sub.maxLength}\``);
  if (sub.pattern) out.push(`- pattern: \`${sub.pattern}\``);
  if (sub.format) out.push(`- format: \`${sub.format}\``);
  if (sub.minItems !== undefined) out.push(`- minItems: \`${sub.minItems}\``);
  if (sub.maxItems !== undefined) out.push(`- maxItems: \`${sub.maxItems}\``);
  if (sub.items) out.push(`- items: \`${sub.items.type || JSON.stringify(sub.items)}\``);
  if (Object.keys(sub.properties || {}).length > 0) {
    out.push('');
    out.push('  Sub-fields:');
    for (const [n, s] of Object.entries(sub.properties)) {
      const req = (sub.required || []).includes(n);
      out.push(`  - \`${n}\` (${req ? '**required**' : 'optional'}): ${s.type || ''}${s.description ? ' — ' + s.description : ''}`);
    }
  }
  out.push('');
  return out.join('\n');
}

/**
 * Top-level dispatcher. spec is a friendly key or path; flags
 * {output, json} configure output.
 */
export async function schemaDocCommand(spec, opts = {}) {
  const path = resolveSchemaPath(spec);
  const raw = readFileSync(path, 'utf8');
  const schema = JSON.parse(raw);
  const stem = spec.replace(/\.json$/, '').split('/').pop();
  const title = stem.charAt(0).toUpperCase() + stem.slice(1);
  const md = renderSchema(schema, title);
  if (opts.output) {
    const out = resolve(opts.output);
    writeFileSync(out, md);
    process.stdout.write(`✓ wrote ${out}\n`);
    return;
  }
  process.stdout.write(md);
}
